language: python

python:
  - 3.5

addons:
  apt:
    packages:
    - enchant

install:
  - wget http://mirrors.kernel.org/ubuntu/pool/main/s/sqlite3/libsqlite3-0_3.11.0-1ubuntu1_amd64.deb
  - sudo dpkg -i libsqlite3-0_3.11.0-1ubuntu1_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/s/sqlite3/sqlite3_3.11.0-1ubuntu1_amd64.deb
  - sudo dpkg -i sqlite3_3.11.0-1ubuntu1_amd64.deb

script:
  - sqlite3 --version
  - python -c 'import sqlite3; print(sqlite3.sqlite_version)'
