language: python

python:
  - 3.5

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
    - enchant
    - sqlite3

script:
  - sqlite3 --version
  - python -c 'import sqlite3; print(sqlite3.sqlite_version)'
